version: '3'

services:
  pm-api:
    container_name: pm-api
    build: ./rest
    volumes:
      - ./rest:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - pm-db

  pm-website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - pm-api

  pm-db:
    container_name: pm-db
    image: postgres
    restart: always
    volumes:
      - ./db/vol:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: docker

  pm-adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080

