FROM python:3.8-slim
WORKDIR /opt/app
COPY ./requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .
CMD ["python", "api.py"]
